# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import argparse
from chat.chat_client_class import *
import _thread
import gol
from PyQt5.QtCore import QStringListModel
import re
import game.ManAndMachine as game_wzc

from PyQt5.QtWidgets import QFileDialog

pattern1 = re.compile(r"'(.*?)':")


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(976, 757)
        self.zx = []
        self.list1 = []
        self.sendButton = QtWidgets.QPushButton(Form)
        self.sendButton.setGeometry(QtCore.QRect(860, 720, 111, 31))
        self.sendButton.setObjectName("sendButton")
        self.MessageRecevingBox = QtWidgets.QPlainTextEdit(Form)
        self.MessageRecevingBox.setGeometry(QtCore.QRect(310, 70, 671, 491))
        self.MessageRecevingBox.setReadOnly(True)
        self.MessageRecevingBox.setObjectName("MessageRecevingBox")
        self.MessageSendingBox = QtWidgets.QLineEdit(Form)
        self.MessageSendingBox.setGeometry(QtCore.QRect(310, 560, 671, 201))
        self.MessageSendingBox.setObjectName("MessageSendingBox")

        self.Clock = QtWidgets.QLCDNumber(Form)
        self.Clock.setGeometry(QtCore.QRect(700, 10, 131, 51))
        self.Clock.setDigitCount(8)
        self.Clock.setObjectName("Clock")
        self.TextingIcon1 = QtWidgets.QLabel(Form)
        self.TextingIcon1.setGeometry(QtCore.QRect(330, 575, 81, 20))
        self.TextingIcon1.setText("")
        self.TextingIcon1.setObjectName("TextingIcon1")
        self.TextingIcon2 = QtWidgets.QLabel(Form)
        self.TextingIcon2.setGeometry(QtCore.QRect(420, 570, 72, 15))
        self.TextingIcon2.setText("")
        self.TextingIcon2.setObjectName("TextingIcon2")
        self.LeaveChatting = QtWidgets.QPushButton(Form)
        self.LeaveChatting.setGeometry(QtCore.QRect(320, 720, 161, 28))
        self.LeaveChatting.setShortcut("")
        self.LeaveChatting.setAutoExclusive(False)
        self.LeaveChatting.setAutoDefault(False)
        self.LeaveChatting.setFlat(False)
        self.LeaveChatting.setObjectName("LeaveChatting")
        self.LogoutButton = QtWidgets.QPushButton(Form)
        self.LogoutButton.setGeometry(QtCore.QRect(870, 40, 93, 28))
        self.LogoutButton.setObjectName("LogoutButton")
        self.VoiceButton = QtWidgets.QPushButton(Form)
        self.VoiceButton.setGeometry(QtCore.QRect(730, 720, 111, 31))
        self.VoiceButton.setObjectName("VoiceButton")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 70, 311, 691))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.QueryButton = QtWidgets.QPushButton(self.frame)
        self.QueryButton.setGeometry(QtCore.QRect(0, 630, 91, 61))
        self.QueryButton.setObjectName("QueryButton")
        self.OfflineGamingButton = QtWidgets.QPushButton(self.frame)
        self.OfflineGamingButton.setGeometry(QtCore.QRect(80, 630, 141, 61))
        self.OfflineGamingButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.OfflineGamingButton.setObjectName("OfflineGamingButton")
        self.friend_lists = QtWidgets.QLabel(self.frame)
        self.friend_lists.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.friend_lists.setObjectName("friend_lists")

        self.OnlineUserListView = QtWidgets.QListView(self.frame)
        self.OnlineUserListView.setGeometry(QtCore.QRect(10, 50, 256, 121))
        self.OnlineUserListView.setObjectName("OnlineUserListView")

        self.Refresh = QtWidgets.QPushButton(self.frame)
        self.Refresh.setGeometry(QtCore.QRect(170, 10, 93, 28))
        self.Refresh.setObjectName("Refresh")
        self.OnlineMemberNum = QtWidgets.QLabel(self.frame)
        self.OnlineMemberNum.setGeometry(QtCore.QRect(120, 10, 72, 21))
        self.OnlineMemberNum.setObjectName("OnlineMemberNum")
        self.RoomInformation = QtWidgets.QLabel(self.frame)
        self.RoomInformation.setGeometry(QtCore.QRect(10, 190, 141, 16))
        self.RoomInformation.setObjectName("RoomInformation")

        self.AllRooms = QtWidgets.QTreeView(self.frame)
        self.AllRooms.setGeometry(QtCore.QRect(10, 230, 256, 192))
        self.AllRooms.setObjectName("AllRooms")

        self.UserIDLabel = QtWidgets.QLabel(Form)
        self.UserIDLabel.setGeometry(QtCore.QRect(840, 10, 141, 21))
        self.UserIDLabel.setObjectName("UserIDLabel")
        self.UserId = QtWidgets.QLabel(Form)
        self.UserId.setGeometry(QtCore.QRect(900, 10, 72, 15))
        self.UserId.setObjectName("UserId")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(600, 720, 111, 31))
        self.pushButton.setObjectName("pushButton")
        self.CurrentRoom = QtWidgets.QListView(Form)
        self.CurrentRoom.setGeometry(QtCore.QRect(850, 120, 111, 181))
        self.CurrentRoom.setObjectName("CurrentRoom")

        self.CurrentRoomLabel = QtWidgets.QLabel(Form)
        self.CurrentRoomLabel.setGeometry(QtCore.QRect(860, 90, 101, 20))
        self.CurrentRoomLabel.setObjectName("CurrentRoomLabel")
        self.MessageRecevingBox.raise_()
        self.MessageSendingBox.raise_()
        self.Clock.raise_()
        self.sendButton.raise_()
        self.TextingIcon1.raise_()
        self.TextingIcon2.raise_()
        self.LeaveChatting.raise_()
        self.LogoutButton.raise_()
        self.VoiceButton.raise_()
        self.frame.raise_()
        self.UserIDLabel.raise_()
        self.UserId.raise_()
        self.pushButton.raise_()
        self.CurrentRoom.raise_()
        self.CurrentRoomLabel.raise_()
        self.listModel = QStringListModel()
        self.listModel.setStringList(self.list1)
        self.OnlineUserListView.setModel(self.listModel)
        self.OnlineUserListView.clicked.connect(self.clicked)
        self.retranslateUi(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sendButton.setText(_translate("Form", "Send"))
        self.LeaveChatting.setText(_translate("Form", "Leave Chatting"))
        self.LogoutButton.setText(_translate("Form", "Logout"))
        self.VoiceButton.setText(_translate("Form", "Voice"))
        self.QueryButton.setText(_translate("Form", "Query"))
        self.OfflineGamingButton.setText(_translate("Form", "Offline Games"))
        self.friend_lists.setText(_translate("Form", "Others:"))
        self.Refresh.setText(_translate("Form", "Refresh"))
        self.OnlineMemberNum.setText(_translate("Form", "0"))
        self.RoomInformation.setText(_translate("Form", "Room Information"))
        self.UserIDLabel.setText(_translate("Form", "UserID:"))
        self.UserId.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "File"))
        self.CurrentRoomLabel.setText(_translate("Form", "Current Room"))
        self.sendButton.clicked.connect(self.send_Button)
        self.LeaveChatting.clicked.connect(self.LeaveChatting_Button)
        self.OfflineGamingButton.clicked.connect(self.OfflineGamingButton_Button)
        self.pushButton.clicked.connect(self.pushButton_Button)
        self.MessageRecevingBox.setPlainText("请选择用户聊天，结束请按Leave Chatting")
        gol.set_value("message", " ")
        QtCore.QMetaObject.connectSlotsByName(Form)
        _thread.start_new_thread(self.time_sx, ())
        _thread.start_new_thread(self.socket1, ())



    def send_Button(self):
        gol.set_value("data", "&" + self.MessageSendingBox.text())
        self.MessageRecevingBox.appendPlainText('[[' + self.UserId.text()+ ']]' + self.MessageSendingBox.text())
        self.MessageSendingBox.setText("")

    def socket1(self):
        parser = argparse.ArgumentParser(description='chat client argument')
        parser.add_argument('-d', type=str, default=None, help='server IP addr')
        args = parser.parse_args()
        client = Client(args, self.UserId.text())
        client.run_chat()

    def time_sx(self):
        while True:
            if gol.get_value("message") != "":
                self.MessageRecevingBox.appendPlainText(gol.get_value("message"))
            gol.set_value("message", "")
            self.Clock.display(time.strftime('%X', time.localtime()))
            people = gol.get_value('logged_in')
            # print(people)
            if str(people) != "{}":
                self.list1 = list(pattern1.findall(str(people)))
            self.listModel.setStringList(self.list1)
            self.OnlineUserListView.setModel(self.listModel)
            try:
                self.OnlineMemberNum.setText(str(int(len(people.split(":")) / 2)))

            except:
                self.OnlineMemberNum.setText("1")

            time.sleep(1)

    def clicked(self, qModelIndex):

        self.zx = self.list1[qModelIndex.row()]
        if self.zx == self.UserId.text():
            self.MessageRecevingBox.setPlainText("不要选自己")
        else:
            gol.set_value("socket_name", self.zx)
            self.MessageRecevingBox.setPlainText("")

    def LeaveChatting_Button(self):
        gol.set_value("data", "&" + "bye")
        gol.set_value("socket_name", {})

    def OfflineGamingButton_Button(self):
        try:
            game_wzc.main()
        except:
            pass

    def pushButton_Button(self):
        _translate = QtCore.QCoreApplication.translate
        directory1 = QFileDialog.getOpenFileName(None, "选择文件", "")
        filename = directory1[0].split("/")[-1]
        f = open(directory1[0], 'r')
        gol.set_value("data", "file&" + filename + "&" + f.read())
        f.close()
        self.MessageRecevingBox.appendPlainText('[[' + self.UserId.text() + ']]' + directory1[0] + "send")